# Generated by Django 2.2 on 2020-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budesocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budesocial',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budesocial',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
