# Generated by Django 2.2 on 2020-11-20 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budesocial', '0002_auto_20201120_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudeSocial',
            new_name='BudeSocialModel',
        ),
    ]
