# Generated by Django 2.2 on 2020-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budesocial', '0003_auto_20201120_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budesocialmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
