# Generated by Django 2.2 on 2020-11-21 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budesocial', '0008_auto_20201121_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budesocialmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
