# Generated by Django 2.2 on 2020-11-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('resetcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoRestAllAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authmode', models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Twitter', 'Twitter'), ('Github', 'Github')], max_length=20)),
                ('token', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('social_id', models.TextField()),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_rest_allauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
