# Generated by Django 2.2 on 2020-11-24 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_allauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangorestallauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_rest_allauth_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
