# Generated by Django 2.2 on 2020-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_allauth', '0002_auto_20201124_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangorestallauth',
            name='authmode',
        ),
        migrations.AddField(
            model_name='djangorestallauth',
            name='provider',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google')], default='Facebook', max_length=20),
            preserve_default=False,
        ),
    ]
